### ISSUE TITLE
[Question] Can I execute one scenario only?

### ISSUE THREAD

**Issue by balanza** [b-yond-infinite-network/jest-cucumber-fusion#10]
### Scenario
I have a feature with one or more scenarios (let's call them X, Y an Z)
I'm developing a test suite
I want to add a new scenario: W
I want to execute only scenario W for faster development cycle

### Problem
There's actually no way to tell `jest` to only run scenario W but temporary removing X, Y and Z from the feature file.

Basically, I'm missing the concept of `scenario` in my tests code. Using regular `jest`'s `describe` I can isolate test cases during development (and even debug it). I'm looking for the same behaviour, but using cucumber-like test definitions.

Is it even possible?

**Comment by bruno-morel** [comment]
It really depends of the tools you're using...but simplified, yes.
All of the jest capabilities are available, including filtering of the test run by name, path, and so on.

Beware though that in the end, you're running an injected, sometime "outlined" (aka with variables/regex), jest test.

For example, if you were to clone this repo, and run `jest -t "Launching my ASCII rocket"`, you will see are port that looks like this: 
<img width="540" alt="Screen Shot 2020-07-21 at 10 54 03 PM" src="https://user-images.githubusercontent.com/662628/88129082-2e985900-cba5-11ea-8d54-97860d0b3412.png">
But it is **just** because it so happen that there is ONE unique Cucumber test with that title (aka jest name).

Now, if you run something a bit more fuzier, in a part where we're using (for example) outlined tests
` jest -t "Selling all of one"   `

You're result will be the running of all test that do match the title "Selling all of one" which is technically 3 tests with different scenario
<img width="520" alt="Screen Shot 2020-07-21 at 10 55 16 PM" src="https://user-images.githubusercontent.com/662628/88129284-b5e5cc80-cba5-11ea-9ccc-8c2dfabad448.png">

That's why it's a **yes, but...** be precise with what you tell jest to filter on...

Let me know if that helps

**Comment by bruno-morel** [comment]
It looks that answered your question or that you moved on, so I'm closing it now, but feel free to open it if you believe it's not resolved.
