### ISSUE TITLE
Cucumber fusion for multiple feature files in Step definition

### ISSUE THREAD

**Issue by testnab100** [b-yond-infinite-network/jest-cucumber-fusion#8]
Currently fusion keyword in stepdefinition file is to include only 1 feature. Can we include all the feature files in stepdefinitions file.

**Comment by bruno-morel** [comment]
Let's make sure I understand what you want:
Currently the Fusion function parse the list of function you defined in the step definition file (JS) and will match them against specific scenarios in the Feature File you specify as a parameter so that we can find all of the related JS Step Definition function to each Gherkin scenario.

You would want the Fusion to match up the just-defined step definition against all the ".feature" file in a directory?
I suppose to centralize all your JavaScript step definition/test function in one giant central place?

**Comment by bruno-morel** [comment]
closed due to no follow up answers
